### ISSUE TITLE
control model

### ISSUE THREAD

**Issue by kynoali** [francofusco/uav_gazebo#8]
i am facing an issue of the 
] [1661436146.061044022, 120.977000000]: Received message for control mode 1, but the current control mode is 0
[ WARN] [1661436147.094654288, 121.987000000]: Received message for control mode 1, but the current control mode is 0
[ WARN] [1661436148.135949150, 122.987000000]: Received message for control mode 1, but the current control mode is 0
[ WARN] [1661436149.162045483, 123.995000000]: Received message for control mode 1, but the current control mode is 0
 when i run the rosrun uav_gazebo example_control.   

secondly, i wanna add addition sensor and control strategies to the drone is it possible

**Comment by francofusco** [comment]
Hi! Sorry for the delay but I am not working on this project anymore (it was more for fun/learning how to do these things).

Anyway, the message tells that the drone is in mode 0 (inactive, see [here](https://github.com/francofusco/uav_gazebo/blob/548e3acec84996a60f7f2b9d4bac073043555b2d/uav_gazebo_msgs/msg/ControlMode.msg)). You probably have to switch to control mode 1 using
```
rostopic pub -1 /drone/switch_mode uav_gazebo_msgs/ControlMode "mode: 1"
```
as written in the [README](https://github.com/francofusco/uav_gazebo#an-example-for-the-impatients).

---
> secondly, i wanna add addition sensor and control strategies to the drone is it possible

Well, you can fork the code and make it work as you wish, but it's probably pointless and would require you to do it... May I suggest considering something else entirely, like [RotorS](https://github.com/ethz-asl/rotors_simulator)? It's perhaps not very easy in the beginning, but it has many more features than my little project 😉

Good luck!

Ps: I am closing the issue, but feel free to reopen it if needed.

**Comment by ishaanbhimwal** [comment]
Hey! 3 years since last msg but I was able to figure it out. The code uses `uav_gazebo_msgs::SwitchMode` service call hence it won't listen to the topic command. We need need to call the service, not publish to a topic.

```
rosservice call /drone/switch_mode "mode: mode: 1"
```
